### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by squerez** [databrickslabs/sandbox#24]
Hi !

I am not sure how to start contributing to this project at the moment and the directive in the repo is not so clear to me.

Let's say I wanted to work on a issue that involves documentation updates - how would that work?

Also,I remember that for dbx, there had to some legal agreement to be signed in the past, not sure if it also applies here?

Let me know and I can edit the contributing markdown with the discussion points.

Also, are there other more direct channels anyone interested in databricks-labs could talk about instead of using issues?

**Comment by squerez** [comment]
Sorry, just found the document, will close this issue!

**Comment by nfx** [comment]
@squerez we have CLA bot that is automating accepting a legal waiver from you, same text, but tracked automatically for the scope of the entire Databricks Labs org (and other orgs soon as well). That means - you can contribute doc updates and fixes :)
